#!/usr/bin/env bash
set -euo pipefail

markdown_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
tiqian_dir="${TIQIAN_CHECKOUT:-$markdown_dir/../tiqian}"
math_dir="${TIQIAN_MATH_CHECKOUT:-$markdown_dir/../tiqian-math}"
suite_version="${1:-${TIQIAN_VERSION:-0.1.0-SNAPSHOT}}"
config="$markdown_dir/.tiqian-local.properties"

if [[ "$suite_version" != *-SNAPSHOT ]]; then
    echo "Local development requires a -SNAPSHOT version, got: $suite_version" >&2
    exit 1
fi

for checkout in "$tiqian_dir" "$math_dir"; do
    if [[ ! -x "$checkout/gradlew" ]]; then
        echo "Gradle checkout not found: $checkout" >&2
        exit 1
    fi
done

gradle_args=(
    --no-daemon
    "-PtiqianVersion=$suite_version"
)

"$tiqian_dir/gradlew" -p "$tiqian_dir" publishTiqianToMavenLocal "${gradle_args[@]}"
"$math_dir/gradlew" -p "$math_dir" publishMathComposeToMavenLocal "${gradle_args[@]}"

temporary_config="$config.tmp"
{
    printf '# Generated by scripts/enable-local-suite.sh.\n'
    printf 'version=%s\n' "$suite_version"
} > "$temporary_config"
mv "$temporary_config" "$config"

printf 'Tiqian local suite enabled at %s.\n' "$suite_version"
printf 'Run scripts/disable-local-suite.sh to return to Maven Central.\n'
